title: Fezza
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Fezza"
job: "Bachelor of Games Development"

phone_number: 0403958680
address: Brisbane, Australia
email: fezzaoffical@gmail.com
linkedin_username:
github_username: f-ezza
instagram_username: _fezza___
twitter_username: FezzaU69558
facebook_username: 
youtube_username: fezza2283
blog_url:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
